[package]
  name = "libloragw-sx1302"
  version = "1.0.0"
  authors = ["Orne Brocaar <info@brocaar.com>"]
  edition = "2024"
  publish = false

[dependencies]
  anyhow = { workspace = true }

[build-dependencies]
  bindgen = { workspace = true }
